included:
  - Extradock
  - ExtradockTests

excluded:
  - Extradock.xcodeproj
  - .build

opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_collection_literal
  - empty_string
  - explicit_init
  - first_where
  - last_where
  - multiline_parameters
  - operator_usage_whitespace
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - sorted_first_last

disabled_rules:
  - trailing_comma
  - todo

line_length:
  warning: 140
  error: 200
  ignores_urls: true
  ignores_comments: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 400
  error: 600

identifier_name:
  min_length:
    warning: 1
    error: 1

reporter: "xcode"
